stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."
  only:
    - develop
    - /^feature\/.*/
    - /^release\/.*/
    - /^hotfix\/.*/

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - main