stages:
    - build
    - test
    - deploy

# Job de compilación
build-job:
    stage: build
    script:
        - echo "Compiling the project..."
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist/

# Job de pruebas
test-job:
    stage: test
    script:
        - echo "Running tests..."
        - npm test

# Job de despliegue
deploy-job:
    stage: deploy
    script:
        - echo "Deploying the project..."
        - npm run deploy
    environment:
        name: production
        url: https://example.com
    only:
        - main
